const { withDangerousMod, withGradleProperties } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getNodePath() {
  try {
    // Try to get node path from environment
    if (process.env.NODE_BINARY) {
      return process.env.NODE_BINARY;
    }

    // Try which node
    const nodePath = execSync('which node', { encoding: 'utf8' }).trim();
    if (nodePath) {
      return nodePath;
    }
  } catch (e) {
    // Fallback to searching NVM
    const homeDir = process.env.HOME || process.env.USERPROFILE;
    const nvmDir = path.join(homeDir, '.nvm', 'versions', 'node');

    if (fs.existsSync(nvmDir)) {
      const versions = fs.readdirSync(nvmDir).sort().reverse();
      if (versions.length > 0) {
        return path.join(nvmDir, versions[0], 'bin', 'node');
      }
    }
  }

  return 'node'; // Fallback
}

module.exports = function withNodePath(config) {
  // Set NODE_BINARY in gradle properties
  config = withGradleProperties(config, (config) => {
    const nodePath = getNodePath();
    config.modResults.push({
      type: 'property',
      key: 'NODE_BINARY',
      value: nodePath,
    });
    return config;
  });

  // Also inject into settings.gradle for pluginManagement
  config = withDangerousMod(config, [
    'android',
    (config) => {
      const settingsGradlePath = path.join(config.modRequest.platformProjectRoot, 'settings.gradle');

      try {
        if (fs.existsSync(settingsGradlePath)) {
          let content = fs.readFileSync(settingsGradlePath, 'utf8');

          if (!content.includes('NODE_BINARY setup')) {
            const nodePath = getNodePath();

            // Set as system property at the very beginning of pluginManagement
            // This makes it available to all plugins including expo-autolinking-settings
            const nodeSetup = `  // NODE_BINARY setup - auto-generated by withNodePath plugin
  def nodeBinary = System.getenv("NODE_BINARY") ?: "${nodePath.replace(/\\/g, '\\\\')}"
  System.setProperty("NODE_BINARY", nodeBinary)
  
`;

            // Inject at the beginning of pluginManagement block
            content = content.replace(/pluginManagement\s*\{/, `pluginManagement {\n${nodeSetup}`);

            // Replace all "node" references in commandLine calls
            content = content.replace(/commandLine\s*\(\s*"node"/g, 'commandLine(nodeBinary');

            fs.writeFileSync(settingsGradlePath, content, 'utf8');
            console.log('✅ Updated settings.gradle with NODE_BINARY path:', nodePath);
          }
        }
      } catch (e) {
        console.warn(`⚠️  Could not update settings.gradle: ${e.message}`);
      }

      return config;
    },
  ]);

  config = withDangerousMod(config, [
    'android',
    (config) => {
      const appBuildGradlePath = path.join(config.modRequest.platformProjectRoot, 'app', 'build.gradle');

      try {
        if (fs.existsSync(appBuildGradlePath)) {
          let content = fs.readFileSync(appBuildGradlePath, 'utf8');

          if (!content.includes('AUTOLINKING TASK ORDER FIX')) {
            const taskOrderFix = `

// AUTOLINKING TASK ORDER FIX - auto-generated by withNodePath plugin
afterEvaluate {
    def packageListTask = tasks.findByName("generateAutolinkingPackageList")
    def newArchTask = tasks.findByName("generateAutolinkingNewArchitectureFiles")
    if (packageListTask != null && newArchTask != null) {
        newArchTask.dependsOn(packageListTask)
    }
}
`;
            content += taskOrderFix;
            fs.writeFileSync(appBuildGradlePath, content, 'utf8');
            console.log('✅ Added autolinking task-order fix to app/build.gradle');
          }
        }
      } catch (e) {
        console.warn(`⚠️  Could not update app/build.gradle: ${e.message}`);
      }

      return config;
    },
  ]);

  return config;
};
